name: Deploy Bucket
on:
  workflow_dispatch:

jobs:
  bucket_deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_wrapper: false

      - name: Authenticating in GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Terraform Plan
        run: |
          cd terraform
          terraform init
          terraform plan

      - name: Terraform apply
        run: |
          cd terraform
          terraform apply -lock=false --auto-approve

  python_test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: bucket_deploy

      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticating in GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r python/requirements.txt

      - name: Run code
        run: |
          chmod +x python/main.py
          python python/main.py